# Generated by Django 2.1.7 on 2019-06-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('desc', models.TextField(blank=True, max_length=256, null=True, verbose_name='个人描述')),
                ('gender', models.CharField(choices=[(0, '女'), (1, '男')], default=1, max_length=4, verbose_name='性别')),
                ('role_power', models.SmallIntegerField(max_length=2, verbose_name='角色权限')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
            ],
            options={
                'verbose_name': '员工信息表',
                'verbose_name_plural': '员工信息表',
                'db_table': 'staff',
            },
        ),
    ]
