# Generated by Django 2.1.7 on 2019-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinfo',
            name='role',
            field=models.CharField(default='', max_length=32, verbose_name='职位名称'),
        ),
    ]
